config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }
  resource :follow, only: [:create, :destroy]
  resource :profile, only: [:edit, :update]
  get 'users/:id', to: 'profiles#show', as: :user_profile
  get '/search', to: 'search#search'

  resources :snap_its, :except => [:index, :edit, :update]
  resource :snap_it_proxy, :only => [:show]
  resources :activities, :only => [:index]

  scope :api do
    scope :v1 do
      resources :snap_it_proxies, :only => [:create]
      resources :snap_it_languages, :only => [:index]
      resources :snap_it_themes, :only => [:index]
      resources :comments, :only => [:index, :create, :destroy]
      resources :likes, :only => [:index, :create, :destroy]
      resources :tags, :only => [:index]
    end
  end

  root 'static_pages#index'

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    if !params[:q] || params[:q].length < 1
      flash[:warning] = 
        "Please enter a longer search term"
      redirect_to_back
    else
      @snap_its = SnapIt
        .search(params[:q])
        .paginate(page: params[:page], per_page: 20)

      users = User.search(params[:q])
      profiles = Profile.search(params[:q])
      @users = User
        .where( id: (users.pluck(:id) + profiles.pluck(:user_id) ) )
        .paginate(page: params[:page], per_page: 20)
    end
  end

end

app/helpers/search_helper.rb
module SearchHelper
  def preview_description(description, query)
    preview_chars = 120
    query = sanitize(query)

    if index = description.index(query)
      trim = query.length + preview_chars
      start = index - trim >= 0 ? index - trim : 0
      preview = description[start..(index + trim)]
      bolded = preview.gsub(query, "<b>#{query}</b>")
      result = sanitize("#{bolded}...")
    else
      result = "#{description[0..preview_chars]}..."
    end
    result.html_safe
  end
end

app/views/search/search.html.erb
<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
  <li role="presentation" class="active">
    <a href="#snapits" aria-controls="snapits" role="tab" data-toggle="tab">SnapIts (<%= @snap_its.count %>)</a>
  </li>
  <li role="presentation">
    <a href="#users" aria-controls="users" role="tab" data-toggle="tab">Users (<%= @users.count %>)</a>
  </li>
</ul>


<div class="search tab-content">
    
    <h2 class="text-center">Search Results (<%= @snap_its.count + @users.count %>)</h2>

    <div role="tabpanel" class="tab-pane active" id="snapits">
      <h3 class="text-center">Snap Its</h3>
      <% if @snap_its.present? %>

        <div class="text-center">
          <%= will_paginate @snap_its, renderer: BootstrapPagination::Rails %>
        </div>

        <div class="row">
          <% @snap_its.each do |snap_it| %>
              
            <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 result">
              <%= link_to(snap_it_path(snap_it)) do %>
                <div class="preview" style="background: url(<%= snap_it.photo.file %>)"></div>
              <% end %>
                
              <h4>
                <%= link_to snap_it.title, snap_it_path(snap_it) %> by  
                <%= link_to snap_it.user.username, user_profile_path(snap_it.user) %>
              </h4>
              <%= preview_description(snap_it.description, params[:q]) %>

              <p>
                Tags:
                <%= snap_it.tags.take(5).map { |tag| link_to("##{tag.name}", search_path(:q => tag.name)) }.join(', ').html_safe %>
              </p>
            </div>

          <% end %>
        </div>

        <div class="text-center">
          <%= will_paginate @snap_its, renderer: BootstrapPagination::Rails %>
        </div>

      <% else %>

        <h4 class="text-center">
          Sorry, I can't find any Snap Its with a matching title or description!
        </h4>

      <% end %>
    </div>

    
    <div role="tabpanel" class="tab-pane" id="users">
      <h3 class="text-center">Users</h3>
      <% if @users.present? %>

        <div class="text-center">
          <%= will_paginate @users, renderer: BootstrapPagination::Rails %>
        </div>

        <div class="row">
          <% @users.each do |user| %>
          
            <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 media result">
              <div class="media-left">
                <%= link_to(user_profile_path(user)) do %>
                  <%= image_tag user.profile.gr_or_avatar(:small), class: 'media-object' %>
                <% end %>
              </div>
              <div class="media-body">
                <div class="pull-right">
                  <%= follow_buttons(user) %>
                </div>
                <h4 class="media-heading">
                  <%= link_to user.username, user_profile_path(user) %>
                </h4>
                <%= user.profile.full_name %>
              </div>
            </div>
          
          <% end %>
        </div>

        <div class="text-center">
          <%= will_paginate @users, renderer: BootstrapPagination::Rails %>
        </div>      

      <% else %>

        <h4 class="text-center">
          Sorry, I can't find any members by that name!
        </h4>

      <% end %>
    </div>

</div>