config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }
  resource :follow, only: [:create, :destroy]
  resource :profile, only: [:edit, :update]
  get 'users/:id', to: 'profiles#show', as: :user_profile
  get '/search', to: 'search#search'

  resources :snap_its, :except => [:index, :edit, :update]
  resource :snap_it_proxy, :only => [:show]
  resources :activities, :only => [:index]

  scope :api do
    scope :v1 do
      resources :snap_it_proxies, :only => [:create]
      resources :snap_it_languages, :only => [:index]
      resources :snap_it_themes, :only => [:index]
      resources :comments, :only => [:index, :create, :destroy]
      resources :likes, :only => [:index, :create, :destroy]
      resources :tags, :only => [:index]
    end
  end

  root 'static_pages#index'

end

app/models/snap_it.rb
class SnapIt < ActiveRecord::Base
  include Dateable
  include Searchable
  include Taggable
  include ActivityFeedable

  searchable_fields :title, :description
  
  taggable_fields :description
  taggable_default_tags ->(snap_it) { [snap_it.snap_it_language.editor_name, snap_it.snap_it_theme.editor_name] }

  activity_feedable_user_methods :user
  activity_feedable_actions :create  


  belongs_to :user
  belongs_to :snap_it_language
  belongs_to :snap_it_theme
  has_one :photo, :as => :attachable, :dependent => :destroy
  has_many :comments, as: :parent, :dependent => :destroy
  has_many :likes, as: :parent, :dependent => :destroy
  has_many :taggings, :as => :taggable, :dependent => :destroy
  has_many :tags, :through => :taggings

  validates :title,
            :presence => true

  validates :description,
            :length => { :maximum => 512 },
            :presence => true

  validates :body,
            :presence => true

  validates :user,
            :presence => true

  validates :snap_it_language,
            :presence => true

  validates :snap_it_theme,
            :presence => true


  accepts_nested_attributes_for :photo


  def self.new_from_token(token)
    snap_it_proxy = SnapItProxy.find_by_token(token)
    if snap_it_proxy
      new({
        :title => snap_it_proxy.title,
        :description => snap_it_proxy.description,
        :body => snap_it_proxy.body,
        :font_size => snap_it_proxy.font_size,
        :wrap_limit => snap_it_proxy.wrap_limit,
        :photo_attributes => { 
          :file => snap_it_proxy.image_data_to_image_file
        },
        :user_id => snap_it_proxy.user.id,
        :snap_it_language_id => snap_it_proxy.snap_it_language_id,
        :snap_it_theme_id => snap_it_proxy.snap_it_theme_id
      })
    else
      new
    end
  end
end

app/controllers/snap_its_controller.rb
class SnapItsController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :new]
  before_action :set_snap_it, :only => [:show, :destroy]


  def show
  end


  def new
    @font_sizes = SnapItProxy::FONT_SIZES
    @snap_it_languages = SnapItLanguage.all
    @snap_it_themes = SnapItTheme.all
  end


  def create
    @snap_it = current_user.snap_its.new_from_token(snap_it_params[:token])
    if @snap_it.save
      flash[:success] = 'SnapIt created'
      redirect_to @snap_it
    else
      flash[:error] = [
        'SnapIt not created ',
        '(likely because no source data was provided): ',
        @snap_it.errors.full_messages.join(', ')
      ].join
      redirect_to new_snap_it_path
    end
  end


  def destroy
    if @snap_it.destroy
      flash[:success] = 'SnapIt destroyed'
      redirect_to user_profile_path(current_user)
    else
      flash[:error] = 'SnapIt not destroyed' +
        @snap_it.errors.full_messages.join(', ')
      redirect_to_back
    end
  end




  private
  def set_snap_it
    collection = action_name == 'show' ? SnapIt : current_user.snap_its
    @snap_it = collection.find_by_id(params[:id])
    redirect_to_back :flash => { :error => 'SnapIt not found' } unless @snap_it
  end


  def snap_it_params
    params.require(:snap_it).permit(
      :token
    )
  end
end

app/helpers/snap_its_helper.rb
module SnapItsHelper
end

app/views/snap_its/_snap_it.html.erb
<div class="panel panel-default">
  <div class="panel-heading clearfix">
    <h2 class="pull-left">
      <%= link_to(snap_it.title, snap_it_path(snap_it)) %>
      by
      <%= link_to(snap_it.user.username, user_profile_path(snap_it.user)) %>
      <br>
      <small>
        Posted on <%= snap_it.date %>
      </small>
    </h2>

    <% if current_user == snap_it.user %>
      <%= link_to(fa_icon('times', :text => 'Delete'), snap_it_path(snap_it), :method => :delete, :class => 'btn btn-danger pull-right btn-vertical-center', :data => { :confirm => 'Are you sure?' }) %>
    <% end %>

  </div>
  <div class="panel-body">
    <div class="snap-it-photo">
      <%= link_to(snap_it_path(snap_it)) do %>
        <img class="img-responsive" src="<%= snap_it.photo.file.url %>" alt="<%= snap_it.title %>">
      <% end %>
    </div>
  </div>
  <div class="panel-footer">
    <p><%= tags_to_links(snap_it.description, snap_it.tags) %></p>

    <div ng-controller="CommentsCtrl">
      <div class="pull-right">
        <a href="javascript:void(0)" ng-click="expandComments = true">
          {{ comments.length }} Comments
        </a>
      </div>

      <likes parent="{type: 'snap_it', id: <%= snap_it.id %>}" current-user-id="<%= current_user ? current_user.id : false %>"></likes>

      <comments parent="{type: 'snap_it', id: <%= snap_it.id %>}" current-user-id="<%= current_user ? current_user.id : false %>" comments="comments" ng-show="expandComments"></comments>
    </div>

  </div>
</div>

app/views/snap_its/_snap_its.html.erb
<% if snap_its.empty? %>

  <div class="panel panel-info">
    <div class="panel-body">
      No SnapIts yet.
    </div>
  </div>

<% else %>

  <% snap_its.each do |snap_it| %>

    <%= render snap_it %>

  <% end %>

<% end %>

app/views/snap_its/new.html.erb
<%# Inject angular app into <html> %>
<% content_for :angular_app do %>
  ng-app="Editor"
  ng-controller="SnapItsCreateCtrl"
<% end %>


<flash-message
    duration="5000"
    show-close="true"
></flash-message>


<header id="main-header" class="page-header text-center">
  <h1>Create a SnapIt</h1>

  <% if user_signed_in? %>
    <%= link_to(fa_icon('camera', :text => 'Preview SnapIt!'), '', :class => 'btn btn-primary', :'ng-click' => 'getPreview()') %>
  <% else %>
    <%= link_to(fa_icon('pencil-square-o', :text => 'Sign Up to Preview!'), new_user_registration_path, :class => 'btn btn-primary') %>
  <% end %>
</header>


<div ng-model="snapIt" ui-ace="{
  useWrapMode: true,
  theme: snapItParams.theme,
  mode: snapItParams.language,
  onLoad: aceLoaded,
  onChange: aceChanged,
  advanced: {
    fontSize: +snapItParams.fontSize
  }
}"></div>


<div class="row" style="border-top-left-radius: 0; border-top-right-radius: 0;">
  <div class="col-xs-12 col-sm-6 form-group">
    <%= label_tag('Title') %>
    <%= text_field_tag('snap_it[title]', nil, :class => 'form-control', :'ng-model' => 'snapItParams.title') %>
  </div>

  <div class="col-xs-12 col-sm-6 form-group">
    <%= label_tag('Description') %>
    <%= text_area_tag('snap_it[description]', nil, :class => 'form-control', :'ng-model' => 'snapItParams.description') %>
  </div>

  <div class="col-xs-12 col-sm-3 form-group">
    <%= label_tag('Language') %>
    <%= select_tag('language', options_for_select(@snap_it_languages.map { |l| [l.name, l.editor_name] }), :'ng-model' => 'snapItParams.language', :class => 'form-control') %>
  </div>

  <div class="col-xs-12 col-sm-3 form-group">
    <%= label_tag('Theme') %>
    <%= select_tag('theme', options_for_select(@snap_it_themes.map { |t| [t.name, t.editor_name] }), :'ng-model' => 'snapItParams.theme', :class => 'form-control') %>
  </div>

  <div class="col-xs-12 col-sm-3 form-group">
    <%= label_tag('Font Size') %>
    <%= select_tag('font_size', options_for_select(@font_sizes), :'ng-model' => 'snapItParams.fontSize', :class => 'form-control', :'ng-change' => 'fontSizeChanged()') %>
  </div>

  <div class="col-xs-12 col-sm-3 form-group">
    <%= label_tag('Wrap Limit') %>
    <%= check_box_tag('wrap-enabled', nil, false, :'ng-model' => 'snapItParams.isWrapEnabled', :'ng-change' => 'wrapEnabledChanged()') %>
    <%= number_field_tag('snap_it[wrap_limit]', nil, :class => 'form-control', :'ng-model' => 'snapItParams.wrapLimit', :'ng-if' => 'snapItParams.isWrapEnabled', :'ng-change' => 'wrapLimitChanged()') %>
  </div>
</div>


<div id="snap-it-preview-modal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h2 class="modal-title">SnapIt Preview</h2>
        <br>
        <%= form_tag(snap_its_path, :method => :post) do %>
          <input type="hidden" name="snap_it[token]" ng-value="snapItParams.token">

          <button type="button" class="btn btn-danger" data-dismiss="modal">
            <%= fa_icon('times', :text => 'Cancel') %>
          </button>
          <button type="submit" class="btn btn-primary">
            <%= fa_icon('camera', :text => 'Create SnapIt') %>
          </button>
        <% end %>
      </div>
      <div class="modal-body" id="snap-it-preview"></div>
      <div class="modal-footer"></div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/snap_its/show.html.erb
<%= render @snap_it %>

<% content_for :angular_app do %>
  ng-app="Social"
<% end %>