config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }
  resource :follow, only: [:create, :destroy]
  resource :profile, only: [:edit, :update]
  get 'users/:id', to: 'profiles#show', as: :user_profile
  get '/search', to: 'search#search'

  resources :snap_its, :except => [:index, :edit, :update]
  resource :snap_it_proxy, :only => [:show]
  resources :activities, :only => [:index]

  scope :api do
    scope :v1 do
      resources :snap_it_proxies, :only => [:create]
      resources :snap_it_languages, :only => [:index]
      resources :snap_it_themes, :only => [:index]
      resources :comments, :only => [:index, :create, :destroy]
      resources :likes, :only => [:index, :create, :destroy]
      resources :tags, :only => [:index]
    end
  end

  root 'static_pages#index'

end

app/views/shared/_flash.html.erb
<% unless flash.empty? %>

  <% flash.each do |key, value| %>
    <div class="main-flash alert alert-<%= flash_css_class(key) %> text-center" style="border-radius: 0;">
      <%= value %>
    </div>
  <% end %>

<% end %>

app/views/shared/_form_error.html.erb
<% unless errors.nil? %> 
  <div class="error-explanation">
    <ul class="list-unstyled">
      <% errors.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav id="main-nav" class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-nav-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to(user_signed_in? ? activities_path : root_path, :class => 'navbar-brand') do %>
        <%= image_tag(logo_url, :class => 'logo sm') %>
        <%= site_title %>
      <% end %>

      <span class="codesnapit-btn-container">
        <%= link_to(new_snap_it_path, :class => 'btn btn-primary btn-codesnapit', :title => 'Create a new CodeSnapIt!') do %>
          <%= image_tag(logo_url, :class => 'img-responsive logo sm logo-normal') %>
          <%= image_tag(logo_url(:white), :class => 'img-responsive logo sm logo-white') %>
        <% end %>
      </span>
    </div>


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="main-nav-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <div class="navbar-avatar">
                <%= image_tag current_user.profile.gr_or_avatar(:small) %>
              </div>
            </a>

            <ul class="dropdown-menu">
              <li>
                <%= link_to(fa_icon('user', :text => 'Edit Profile'), edit_profile_path(current_user.profile)) %>
              </li>
              <li>
                <%= link_to(fa_icon('clock-o', :text => 'Timeline'), user_profile_path(current_user)) %>
              </li>
              <li>
                <%= link_to(fa_icon('cog', :text => 'Account Settings'), edit_user_registration_path) %>
              </li>
            </ul>
          </li>
          
          <li>
            <form>
              <%= link_to "Logout", destroy_user_session_path, class: "btn btn-link navbar-btn", method: :delete  %>
            </form>
          </li>

        <% else %>     

          <li>
            <!-- bs3 hack for buttons inside li in navbar -->
            <form>
              <%= link_to "Sign Up!", new_user_registration_path, class: "btn btn-primary navbar-btn"  %>
            </form>
          </li>
          <li>
            <form>
              <%= link_to "Login", new_user_session_path, class: "btn btn-link navbar-btn" %>
            </form>
          </li>

        <% end %>

      </ul>
      <form action="<%= search_path %>" method="get" class="navbar-form navbar-right" role="search">        
        <div class="form-group">
          <div class="input-group search-bar">
            <%= text_field_tag :q, params[:q], class: "form-control", placeholder:"Find SnapIts/Users" %>
            <span class="input-group-btn">
              <button class="btn btn-default" type="submit" name="search">
                <i class="fa fa-search" aria-hidden="true"></i>
                <span class="sr-only">Search</span>
              </button>
            </span>
          </div>
        </div>      
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>